baseURL = 'https://frederiklarsen.com/'
languageCode = 'en-us'
title = 'Frederik Larsen'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params.profileMode]
enabled = true
title = "Frederik Larsen"
subtitle = "My personal website."

[[menu.main]]
identifier = "LocalGovStatBank"
name = "LocalGovStatBank"
url = "https://frederiklarsen.com/LocalGovStatBank"
weight = 10

[[menu.main]]
identifier = "NoegletalR"
name = "NoegletalR"
url = "https://cran.r-project.org/web/packages/noegletalR/index.html"
weight = 20
