baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Frederik Larsen'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params.profileMode]
enabled = true
title = "Frederik Larsen"
subtitle = "My personal website."